Traceback (most recent call last):
  File "/Users/olga/PycharmProjects/MiraApp/main.py", line 255, in main
    app = MobileApp()
  File "/Users/olga/PycharmProjects/MiraApp/main.py", line 67, in __init__
    self.load_all_kv_files()
  File "/Users/olga/PycharmProjects/MiraApp/main.py", line 175, in load_all_kv_files
    Builder.load_file('{}/{}'.format(directory_kv_files, kv_files))
  File "/Users/olga/PycharmProjects/MiraApp/venv/lib/python3.7/site-packages/kivy/lang/builder.py", line 304, in load_file
    data = fd.read()
  File "/usr/local/bin/../../../Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
